name: Update badges
on: workflow_dispatch
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_SORT: RECENT
          CREDLY_USER: piers@ringwraith.org
